services:
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: device_db
      DB_USER: postgres
      DB_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d device_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s # Give the DB some time to start initially

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy # Wait until postgres is healthy

volumes:
  postgres_data: